/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetocarro;



/**
 *
 * @author heito
 */
public class Tela3 extends javax.swing.JFrame {

    /**
     * Creates new form Tela3
     */
    public Tela3() {
        initComponents();
        acl.setVisible(false);
        aclt.setVisible(false);
        aclb.setVisible(false);
        voltar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digite = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        botao = new javax.swing.JButton();
        acl = new javax.swing.JLabel();
        aclt = new javax.swing.JTextField();
        aclb = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        res = new javax.swing.JLabel();
        uwu = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("Qual função você quer executar?");

        botao.setText("Confirmar");
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        acl.setText("Quanto você deseja acelerar?");

        aclb.setText("confirmar");
        aclb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aclbActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acl)
                            .addComponent(digite, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uwu)
                            .addComponent(botao))))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aclb))
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(aclt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(res)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(digite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uwu)
                .addGap(36, 36, 36)
                .addComponent(acl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aclt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aclb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(res)
                .addGap(7, 7, 7)
                .addComponent(voltar)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
           
    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        Carro c1 = new Carro();
        c1.nome = "UNO";
        c1.marca = "FIAT";
        c1.ano = 2015;
        c1.vel = 120;
        
        
        Moto m1 = new Moto();
        m1.nomeM = "Panigale";
        m1.marcaM = "Ducati";
        m1.anoM = 2019;
        m1.velM = 70;
        
        Kombi k1 = new Kombi();
        
        k1.nomeK = "Kombi";
        k1.marcaK = "Volkswagen";
        k1.anoK = 1957;
        k1.velK = 90;
        
        Jetsky j1 = new Jetsky();
        
        j1.marcaJ = "Sea-Doo";
        j1.nomeJ = "Spark Trixx";
        j1.anoJ = 2025;
        j1.velJ = 100;
        
        Triciclo t1 = new Triciclo();
        t1.marcaT = "Yamaha";
        t1.nomeT = "Niken GT";
        t1.anoT = 2019;
        t1.velT = 200;
        
        if(digite.getText().equals("acelerar")){
            uwu.setText("");
            titulo.setVisible(false);
            digite.setVisible(false);
            botao.setVisible(false);
            
            acl.setVisible(true);
            aclt.setVisible(true);
            aclb.setVisible(true);
            voltar.setVisible(true);
        }
        if(digite.getText().equals("freiar")){
            freiarC f = new freiarC();
            f.setVisible(true);
            this.dispose();
        }
        if(digite.getText().equals("buzinar")){
            uwu.setText("Carro Buzinando");
        }
    }//GEN-LAST:event_botaoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        res.setText("");
        acl.setVisible(false);
        aclt.setVisible(false);
        aclb.setVisible(false);
        voltar.setVisible(false);
        
        titulo.setVisible(true);
        digite.setVisible(true);
        botao.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void aclbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aclbActionPerformed
        Carro c1 = new Carro();
        c1.nome = "UNO";
        c1.marca = "FIAT";
        c1.ano = 2015;
        c1.vel = 120;
        
        
        Moto m1 = new Moto();
        m1.nomeM = "Panigale";
        m1.marcaM = "Ducati";
        m1.anoM = 2019;
        m1.velM = 70;
        
        Kombi k1 = new Kombi();
        
        k1.nomeK = "Kombi";
        k1.marcaK = "Volkswagen";
        k1.anoK = 1957;
        k1.velK = 90;
        
        Jetsky j1 = new Jetsky();
        
        j1.marcaJ = "Sea-Doo";
        j1.nomeJ = "Spark Trixx";
        j1.anoJ = 2025;
        j1.velJ = 100;
        
        Triciclo t1 = new Triciclo();
        t1.marcaT = "Yamaha";
        t1.nomeT = "Niken GT";
        t1.anoT = 2019;
        t1.velT = 200;
        
        c1.acelerar(Integer.parseInt(aclt.getText()));
        res.setText("A sua velocidade foi para: "+c1.vel+"Km/h");
    }//GEN-LAST:event_aclbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tela2 tela2 = new Tela2();
        tela2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acl;
    private javax.swing.JButton aclb;
    private javax.swing.JTextField aclt;
    private javax.swing.JButton botao;
    private javax.swing.JTextField digite;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel res;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel uwu;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
